# fly.toml app configuration file generated for notakto on 2023-10-08T01:32:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "notakto"
primary_region = "lhr"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[env]
  PHX_HOST = "notakto.khaledhamam.com"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
